name: $(Date:yyyyMMdd).$(Rev:r)

trigger:
  batch: true
  branches:
    include: [ "master" ]
  paths:
    exclude: [ "README.md" ]

jobs:
  - job: build
    displayName: "build"
    pool:
      vmImage: "ubuntu-latest"
    container: 
      image: "debian:buster"
      options:  "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
    workspace:
      clean: all
    timeoutInMinutes: 240

    strategy:
      matrix:
        plct-nuclei-w32:
          SOURCE_GIT_URL: 'https://github.com/qemu/qemu.git'
          SOURCE_GIT_REF: 'staging'
          CROSS_PREFIX: 'i686-w64-mingw32-'
          CROSS_SUFFIX: "w32"
          MAKE_FLAGS: "-j2"
        plct-nuclei-w64:
          SOURCE_GIT_URL: 'https://github.com/qemu/qemu.git'
          SOURCE_GIT_REF: 'staging'
          CROSS_PREFIX: 'x86_64-w64-mingw32-'
          CROSS_SUFFIX: "w64"
          MAKE_FLAGS: "-j2"

    steps:
    
    # work around privilege problem
    # reference: https://github.com/microsoft/azure-pipelines-agent/issues/2043#issuecomment-687983301
    - bash: |
        /tmp/docker exec -t -u 0 ci-container \
        sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
      displayName: 'install sudo'

    - bash: 'sudo -EH bash ./build-stage1.sh'
      displayName: 'prepare environment'

    - bash: 'bash ./build-stage2.sh'
      displayName: 'build'

    - bash: |
        cp -v /tmp/qemu-build/qemu-setup-*.exe "${BUILD_ARTIFACTSTAGINGDIRECTORY}"
        tar -cvJf "${BUILD_ARTIFACTSTAGINGDIRECTORY}/artifacts.tar.xz" /tmp/qemu-build
        tar -cvJf "${BUILD_ARTIFACTSTAGINGDIRECTORY}/installer.tar.xz" /tmp/qemu-nsis
      displayName: 'copy artifacts'

    - task: PublishBuildArtifacts@1
      displayName: 'public artifacts'
      inputs:
        artifactName: 'qemu-build-$(CROSS_SUFFIX)'
